# Generated by Django 3.0.1 on 2020-01-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
