# Generated by Django 3.0.1 on 2020-02-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_author2book_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
