# Generated by Django 3.0.3 on 2020-02-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_emp_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='poll_count',
            field=models.IntegerField(default=100),
        ),
    ]
